# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='published_date',
        ),
    ]
